src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $contenu;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\OneToMany(targetEntity=Categorie::class, mappedBy="article")
     */
    private $categorie;

    public function __construct()
    {
        $this->categorie = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(?string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(?\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >=0 ? '+' : '-';
        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function upVote(): self
    {
        $this->votes++;
        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;
        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
            $categorie->setArticle($this);
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        if ($this->categorie->removeElement($categorie)) {
            // set the owning side to null (unless already changed)
            if ($categorie->getArticle() === $this) {
                $categorie->setArticle(null);
            }
        }

        return $this;
    }

}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class)
            ->add('contenu', TextareaType::class)
            ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\ArticleType;
use Doctrine\ORM\EntityManagerInterface;
use Faker\Factory;
use Faker\Provider\DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Article;

class ArticleController extends AbstractController
{
    //Fonction gérant le tri des nombres pairs et impairs
    static function triNb($nb): array
    {
        $table = [];

        for ($i = 0; $i < $nb; $i++) {
            $alea = rand(0, 99);

            if (fmod($alea, 2) == 0) {
                array_unshift($table, $alea);

            } else {
                $table[] = $alea;
            }
        }
        return $table;
    }

    //Fonction générant des mots aléatoires
    static function stringTab($nb)
    {
        $faker = Factory::create();
        $tab = [];
        for ($i = 0; $i < $nb; $i++) {
            $tab[] = $faker->word();
        }
        return $tab;
    }

    //Liste des articles générés en dehors de la db
    /**
     * @Route("/article", name="app_article")
     */
    public function index(): Response
    {
        return $this->render('article/index.html.twig', [
            'controller_name' => 'ArticleController',
        ]);
    }

    //Affichage d'un article qui n'existe pas en db
    /**
     * @Route("/article/{numero}", name="afficher_article")
     */

    public function afficher($numero): Response
    {
        return $this->render('article/article.html.twig', [
            'controller_name' => 'ArticleController',
            'numArticle' => $numero,
        ]);
    }

    //Affichage des tableaux
    /**
     * @Route("/tableau", name="app_tableau")
     */
    public function tableau(): Response
    {
        $tableTri = self::triNb(10);
        return $this->render('article/tableau.html.twig', [
            'controller_name' => 'ArticleController',
            'triNb' => $tableTri,
        ]);

        $stringTab = self::stringTab(10);
        return $this->render('article/tableau.html.twig', [
            'controller_name' => 'ArticleController',
            'stringTab' => $stringTab,
        ]);
    }

    //Gestion des votes factices des articles hors db
    /**
     * @Route("/article/{numero}/vote/{direction}")
     */

    public function vote($numero, $direction)
    {
        if ($direction === 'up') {
            $compteVote = rand(7, 99);
        } else {
            $compteVote = rand(0, 5);
        }

        return new JsonResponse(['votes' => $compteVote]);
    }


    //Générer un nouvel article en db avec faker
    /**
     * @Route("/newarticle", name="new")
     */

    public function new(EntityManagerInterface $entityManager)
    {
        $faker = Factory::create('fr_FR');
        $titre = $faker->words(3, true);
        $contenu = $faker->paragraph(6);

        $article = new Article();
        $article->setTitre($titre);
        $article->setContenu($contenu);
        $article->setDateCreation(DateTime::dateTime());
        //$article->setDateCreation(DateTime::dateTimeBetween('-1 years', '-11 months'));
        $entityManager->persist($article);
        $entityManager->flush();

        return $this->render('article/newarticle.html.twig');
    }

    //Lister tous les articles en db
    /**
     * @Route("/allarticles", name="allArticles")
     */
    public function article(EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Article::class);
        $listeArticles =  $repository->findAll();

        return $this->render('article/showmulti.html.twig', [
            'articles' => $listeArticles
        ]);
    }

    //Afficher un article via son id
    /**
     * @Route("/article/show/{id}", name="showById")
     */

    public function showById($id, EntityManagerInterface $entityManager)
    {
        $repository = $entityManager->getRepository(Article::class);

        $article = $repository->find($id);

        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    //Lister les articles contenant un mot passé en paramètre
    /**
     * @Route("/article/show/select/{content}", name="showByContent")
     */
    public function showByContent($content, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Article::class);
        $articles = $repository->findByContent($content);

        return $this->render('article/showmulti.html.twig', [
            'articles' => $articles,
        ]);
    }

    //Lister les articles par année
    /**
     * @Route("/article/showyear/{year}", name="showByYear")
     */
    public function showByYear($year, EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Article::class);
        $articles = $repository->findByYear($year);

        return $this->render('article/showmulti.html.twig', [
            'articles' => $articles,
        ]);
    }

    //Afficher un article via son id
    /**
     * @Route("/article/afficher/{id}", name="afficherById")
     */
    public function afficherById(Article $article): Response
    {

        return $this->render('article/show.html.twig', [
            'article' => $article,
        ]);
    }

    //Gestion du système de vote des articles
    /**
     * @Route("/article/{id}/voter", name="article_vote", methods="POST")
     */
    public function articleVote(Article $article, Request $request, EntityManagerInterface $entityManager)
    {
        $direction = $request->request->get('direction');

        if ($direction === 'up') {
        // $article->setVotes($article->getVotes() + 1);
            $article->upVote();
        } elseif ($direction === 'down') {
        // $article->setVotes($article->getVotes() - 1);
            $article->downVote();
        }
        $entityManager->flush();

        return $this->redirectToRoute('afficherById', [
            'id' => $article->getId()
        ]);


    }

    /**
     * @Route("/addarticle", name="addArticle")
     */
    public function add(Request $request): Response
    {
        $article = new Article();
        $article->setDateCreation(DateTime::dateTime());
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $article = $form->getData();
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();
            return $this->redirectToRoute('afficherById', [
                'id' => $article->getId()
            ]);
        }

        return $this->render('article/add.html.twig', [
            'form' => $form->createView()
        ]);
    }

}

templates/article/add.html.twig
{% extends 'base.html.twig' %}

{%  form_theme form _self %}

{% block title %}Nouvel Article{% endblock %}

{% block body %}

    <div class="form-group col-lg-5">

    {{ form_start(form) }}

    {{ form_row(form.titre) }}

    {{ form_row(form.contenu) }}


    <button type="submit" class="btn btn-primary">
        Enregistrer l'article
        <i class="fas fa-save"></i>
    </button>
    </div>

    {{ form_end(form) }}
{% endblock %}

{% block form_row %}
    <div class="form-group col-lg-12">
        {{ form_label(form) }}
        {{ form_widget(form, {'attr': {'class':'form-control form-control-lg'}}) }}
    </div>

{% endblock %}

templates/article/article.html.twig
{% extends 'base.html.twig' %}

{% set numero = numArticle %}

{% block title %}Article numéro {{ numero }} {% endblock %}

{% block body %}

    <h2>L'article numéro {{ numero }}</h2>
    <p>Nullam quis risus eget <a href="{{ path ('app_article') }}">urna mollis ornare</a> vel eu leo. Cum sociis natoque penatibus et magnis dis
        parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.</p>

    <img src="https://picsum.photos/500/300">


    <figure>
        <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>

        </blockquote>
        <figcaption class="blockquote-footer">
            Quelqu'un d'inspiré, <cite title="Source Title">Article{{ numero }}</cite>
        </figcaption>
    </figure>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab enim explicabo illum laudantium nihil obcaecati
        perferendis quaerat, quod reprehenderit voluptate! Accusantium, obcaecati, tempore! Dolores est fugiat iure
        quibusdam sint. In?</p>

    <div class="vote-arrows flex-fill pt-2 js-vote-arrows" style="min-width: 90px;">
        <a class="vote-up" href="#" data-direction="up"><i class="far fa-arrow-alt-circle-up"></i></a>
        <a class="vote-down" href="#" data-direction="down"><i class="far fa-arrow-alt-circle-down"></i></a>
        <span>+ <span class="js-vote-total">6</span></span>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/article_vote.js') }}"></script>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index des articles{% endblock %}

{% block body %}

    <h1>Bienvenue</h1>
    <h2>Veuillez sélectionner un article </h2>

    <a type="button" class="btn btn-primary" href="{{ path ('afficher_article', {numero:'1'}) }}">Article 1</a>
    <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'2'}) }}">Article 2</a>
    <a type="button" class="btn btn-primary" href="{{ path ('afficher_article', {numero:'3'}) }}">Article 3</a>
    <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'4'}) }}">Article 4</a>
    <br>
    <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'5'}) }}">Article 5</a>
    <a type="button" class="btn btn-primary" href="{{ path ('afficher_article', {numero:'6'}) }}">Article 6</a>
    <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'7'}) }}">Article 7</a>
    <a type="button" class="btn btn-primary" href="{{ path ('afficher_article', {numero:'8'}) }}">Article 8</a>

{# autre manière d'afficher les articles
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group me-2" role="group" aria-label="First group">
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'1'}) }}">1</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'2'}) }}">2</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'3'}) }}">3</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'4'}) }}">4</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'5'}) }}">5</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'6'}) }}">6</a>
            <a type="button" class="btn btn-secondary" href="{{ path ('afficher_article', {numero:'7'}) }}">7</a>

        </div>
    </div>
#}
{% endblock %}

templates/article/newarticle.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<h3>Un nouvel article a été généré en base de donnée !</h3>

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage d'un article{% endblock %}

{% block body %}

        <h1>Article : {{ article.titre }} </h1>
        <h4>Date de rédaction : {{ article.dateCreation|date("d/m/Y") }} </h4>
        <img src="https://picsum.photos/500/300">
        <p>Contenu : {{ article.contenu }} </p>
        {# <h4>Vote formaté en string {{ article.votesString }} </h4>  #}
        <form action="{{ path('article_vote', { id: article.id }) }}" method="POST">
                <div class="vote-arrows vote-arrows-alt flex-fill pt-2" style="min-width: 90px;">
                        <button class="vote-up btn btn-link" name="direction" value="up"><i class="fa fa-solid fa-heart"></i></button>
                        <button class="vote-down btn btn-link" name="direction" value="down"><i class="fa fa-solid fa-poop"></i></button>
                        <span>{{ article.votesString }}</span>
                </div>
        </form>
{% endblock %}

templates/article/showmulti.html.twig
{% extends 'base.html.twig' %}

{% block title %}Affichage d'un article{% endblock %}

{% block body %}

    <h2> Vos articles :</h2>
    <br>

    {% for article in articles %}

        <a class="btn btn-primary" href="{{ path('afficherById', { id: article.id }) }}">
        <h4>Article : {{ article.titre }} </h4></a>
        <h5>Date de rédaction : {{ article.dateCreation|date("d/m/Y") }} </h5>
        <p>Contenu : {{ article.contenu }} </p>
        <span><p>Votes de l'article : {{ article.votesString }}</p></span>
        <br>

    {% endfor %}


{% endblock %}

templates/article/tableau.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Tableau !{% endblock %}

{% block body %}

{% set tableNb = triNb %}

    <h1>Tableaux</h1>

    <h2>Tableau de nombres aléatoires</h2>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="row">Nombres aléatoires : {{ tableNb|length }}</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for nb in tableNb %}
                <td>{{ nb }}</td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
    </br>

{# {% set stringTab = stringTab %}

    <h2>Tableau de strings</h2>
    <span class="table table-hover">{{ stringTab }}</span>
#}
{% endblock %}